modLoader="javafml" #mandatory
loaderVersion="[39,)"
license="All Rights Reserved"
[[mods]]
modId="stf"
version="1.2.0" #mandatory
displayName="StarForge" #mandatory
authors="Syconn" #optional
description='''
Travel To a world Far Away. Meet your favorite Star Wars Characters and adventure in custom dimensions and biome.
'''
[[dependencies.stf]]
   modId="forge"
   mandatory=true
   versionRange="[39,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.stf]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.4,1.20)"
   ordering="NONE"
   side="BOTH"

[[dependencies.stf]]
   modId="jei"
   mandatory=false
   versionRange="[12.1.1,)"
   ordering="AFTER"
   side="CLIENT"
[[dependencies.stf]]
   modId="catalogue"
   mandatory=false
   versionRange="[1.2.0,)"
   ordering="NONE"
   side="CLIENT"
